### ISSUE TITLE
Problem Using Grid _aureliaFramework.skipContentProcessing

### ISSUE THREAD

**Issue by FourieDeWet** [CharlesPockert/aurelia-bs-grid#71]
Started using your grid and like what you've done with it. We are trying to use it on one of our project but we are getting the following error and cannot get it to work. Are we doing something wrong?

```
Unhandled promise rejection Error: (0 , _aureliaFramework.skipContentProcessing) is not a function
    Error loading http://localhost:9100/jspm_packages/github/charlespockert/aurelia-bs-grid@0.0.4/grid/grid.js
    at http://localhost:9100/jspm_packages/github/charlespockert/aurelia-bs-grid@0.0.4/grid/grid.js:676:54
    at Object.<anonymous> (http://localhost:9100/jspm_packages/github/charlespockert/aurelia-bs-grid@0.0.4/grid/grid.js:679:4)
    at i (http://localhost:9100/jspm_packages/system.js:5:10766)
    at i (http://localhost:9100/jspm_packages/system.js:4:31855)
    at n (http://localhost:9100/jspm_packages/system.js:4:30420)
    at Object.execute (http://localhost:9100/jspm_packages/system.js:5:3451)
    at b (http://localhost:9100/jspm_packages/system.js:4:9948)
    at w (http://localhost:9100/jspm_packages/system.js:4:10327)
    at p (http://localhost:9100/jspm_packages/system.js:4:8205)
    at h (http://localhost:9100/jspm_packages/system.js:4:8590)
```

Any ideas?

**Comment by charlespockert** [comment]
If you are using the latest release with an up to date Aurelia framework you will probably get issues

The framework API changed in places a few times.

The master branch will probably work done with the latest Au beta so give that a try first for now

**Comment by denimaaark** [comment]
I have same problem and deed not understand what means "The master branch will probably work done with the latest Au beta so give that a try first for now" ??

What to do ?

**Comment by denimaaark** [comment]
I have seen now that aurelia-bs-grid downloads old aurelia versions from github, and doas not use jspm installed versions ?!? I have try to install grid to new aurelia navigation app ...

**Comment by denimaaark** [comment]
solution is jspm install github:charlespockert/aurelia-bs-grid@master

**Comment by FourieDeWet** [comment]
Great, thanks [denimaaark](https://github.com/denimaaark) for the solution!
